services:
  imagnus-app:
    image: gcr.io/imagnus-432717/imagnus-fastapi:v1  # Replace with your FastAPI app image
    container_name: imagnus-app
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://imagnus_user:imagnus_password@postgres-db:5432/imagnus_db
    networks:
      - imagnus-network

  postgres-db:
    image: postgres:15
    container_name: imagnus-postgres
    environment:
      POSTGRES_USER: imagnus_user
      POSTGRES_PASSWORD: imagnus_password
      POSTGRES_DB: imagnus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - imagnus-network

networks:
  imagnus-network:

volumes:
  postgres_data:
